import assert from 'node:assert/strict';
import { readFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from 'playwright';
import sharp from 'sharp';

const indexed = process.env.SITE_INDEXING !== 'false';
const origin = process.env.SITE_URL || 'https://officialasit.github.io';
const base = process.env.SITE_BASE || '/';
const path = `/${base.replace(/^\/+|\/+$/g, '')}`.replace(/\/$/, '') + '/';
const canonical = new URL(path, origin).href;
const html = await readFile('dist/index.html', 'utf8');
const robots = await readFile('dist/robots.txt', 'utf8');
const sitemap = await readFile('dist/sitemap.xml', 'utf8');
const lab = await readFile('dist/style-lab/index.html', 'utf8');
const guide = await readFile('dist/guides/install-cricket-26-mods/index.html', 'utf8');
const guideUrl = new URL('guides/install-cricket-26-mods/', canonical).href;
const browserTmp = resolve('.cache/browser-tmp');
await mkdir(browserTmp, { recursive: true });
process.env.TEMP = browserTmp;
process.env.TMP = browserTmp;
const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  const page = await browser.newPage({ javaScriptEnabled: false });
  await page.route('**/*', route => route.abort());
  await page.setContent(html);
  const getMeta = async (attribute, key) => page.locator(`meta[${attribute}="${key}"]`).getAttribute('content');
  assert.equal(await page.locator('link[rel="canonical"]').getAttribute('href'), canonical);
  assert.equal(await getMeta('property', 'og:url'), canonical);
  assert.equal(await getMeta('property', 'og:title'), await page.title());
  assert.equal(await getMeta('name', 'twitter:title'), await page.title());
  assert.equal(await getMeta('name', 'description'), await getMeta('property', 'og:description'));
  assert.equal(await getMeta('name', 'description'), await getMeta('name', 'twitter:description'));
  assert.equal(await getMeta('property', 'og:image'), new URL('images/social-preview.jpg', canonical).href);
  assert.equal(await getMeta('name', 'twitter:image'), await getMeta('property', 'og:image'));
  const directives = await getMeta('name', 'robots');
  assert.equal(directives.includes('noindex'), !indexed);
  assert.equal(await page.locator('h1').count(), 1);
  const graph = JSON.parse(await page.locator('script[type="application/ld+json"]').textContent())['@graph'];
  assert.equal(graph.length, 4);
  assert.equal(new Set(graph.map(node => node['@id'])).size, graph.length);
  const webpage = graph.find(node => Array.isArray(node['@type']) && node['@type'].includes('FAQPage'));
  const questions = await page.locator('.faq-list details').evaluateAll(details => details.map(d => ({ name: d.querySelector('summary').textContent.trim(), answer: d.querySelector('p').textContent.trim() })));
  assert.deepEqual(webpage.mainEntity.map(q => ({ name: q.name, answer: q.acceptedAnswer.text })), questions);
  assert.ok(graph.filter(node => node['@type'] === 'SoftwareApplication').every(node => !node.downloadUrl && !node.aggregateRating && !node.offers), 'Do not invent downloads, reviews or sale offers');
  assert.ok(graph.every(node => node['@id'].startsWith(canonical)));
  const brokenAnchors = await page.locator('a[href^="#"]').evaluateAll(links => links.filter(a => !document.getElementById(a.hash.slice(1))).map(a => a.hash));
  assert.deepEqual(brokenAnchors, []);
  const parsedSitemap = await page.evaluate(xml => {
    const doc = new DOMParser().parseFromString(xml, 'application/xml');
    return { errors: doc.querySelectorAll('parsererror').length, urls: [...doc.querySelectorAll('loc')].map(e => e.textContent) };
  }, sitemap);
  assert.equal(parsedSitemap.errors, 0);
  assert.deepEqual(parsedSitemap.urls, indexed ? [canonical, guideUrl] : []);
  assert.ok(robots.includes('Allow: /'));
  assert.equal(robots.includes(`Sitemap: ${new URL('sitemap.xml', canonical).href}`), indexed);
  assert.equal(await page.locator('link[rel="sitemap"]').count(), indexed ? 1 : 0);
  await page.setContent(guide);
  assert.equal(await page.locator('link[rel="canonical"]').getAttribute('href'), guideUrl);
  assert.equal(await getMeta('property', 'og:url'), guideUrl);
  assert.equal(await getMeta('property', 'og:title'), await page.title());
  assert.equal(await getMeta('name', 'description'), await getMeta('property', 'og:description'));
  assert.equal((await getMeta('name', 'robots')).includes('noindex'), !indexed);
  assert.equal(await page.locator('h1').count(), 1);
  const guideGraph = JSON.parse(await page.locator('script[type="application/ld+json"]').textContent())['@graph'];
  assert.ok(guideGraph.every(node => node['@id'].startsWith(guideUrl)));
  const guideAnchors = await page.locator('a[href^="#"]').evaluateAll(links => links.filter(a => !document.getElementById(a.hash.slice(1))).map(a => a.hash));
  assert.deepEqual(guideAnchors, []);
  await page.setContent(lab);
  assert.match(await getMeta('name', 'robots'), /noindex/);
  const image = await sharp('public/images/social-preview.jpg').metadata();
  assert.equal(image.width, 1200);
  assert.equal(image.height, 630);
  console.log(`PASS: ${indexed ? 'indexed' : 'staging'} SEO metadata, canonical/base path, social image, FAQ/schema parity, install guide, sitemap, robots and internal anchors.`);
} finally { await browser.close(); }
